# Generated by cpp11: do not edit by hand

decimal_to_fraction <- function(x, base_10, max_denom) {
  .Call(`_fracture_decimal_to_fraction`, x, base_10, max_denom)
}

gcd <- function(x) {
  .Call(`_fracture_gcd`, x)
}

lcm <- function(x, max) {
  .Call(`_fracture_lcm`, x, max)
}
