# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decimal_to_fraction <- function(x, base_10, max_denom) {
    .Call(`_fracture_decimal_to_fraction`, x, base_10, max_denom)
}

gcd <- function(x) {
    .Call(`_fracture_gcd`, x)
}

lcm <- function(x, max = 1e7L) {
    .Call(`_fracture_lcm`, x, max)
}

